options:
  password:
    type: string
    default: "admin"
    description: |
      This sets the password that will be used.
  plonemode:
    type: string
    default: "standalone"
    description: |
      This sets the setup standalone vs zeo that will be used.
