#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

su ploneuser -c '/home/ploneuser/Plone/zinstance/bin/instance start'
